version: '3.8'

services:
  postgres-test:
    image: postgres:15
    container_name: todo-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_test
    ports:
      - "5433:5432"  # Другой порт, чтобы не конфликтовать
    tmpfs: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10